app:
  canvas:
    boundry-horizontal-char: '-'
    boundry-vertical-char: '|'
    default-fill-char: ' '
    rectangle-char: 'x'
    line-char: 'X'
  messages:
    exception:
      invalid-command-no-canvas: This is an invalid command. Please create a canvas first. Run -> C <length> <height>. Try again.""This is an invalid command. Please create a canvas first. Run -> C <length> <height>. Try again.
      invalid-command-wrong-args: Entered command is invalid. Please review the parameters passed and try again
      invalid-Command-diagonal-line: Creation of diagonal line not allowed. Please enter points having equal x or y coordinates.
      command-not-supported: This command is not supported at the moment.